CREATE OR REPLACE PROCEDURE DB_UOC_PROD.DD_OD.FACT_DOCENCIA_LOADS()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS 'begin
let start_time timestamp_ntz := convert_timezone(''America/Los_Angeles'',''Europe/Madrid'', current_timestamp()::timestamp_ntz);
let execution_time float;

-- Carrega de la taula amb tots els registres de la taula STAGE_DOCENCIA_POST

-- Carrega de la taula FACT_DOCENCIA des de la taula STAGE_DOCENCIA_POST. En aquest objecte eliminem qualsevol referencia als codis original i mantenim unicament la informacio dels IDs de les dimensions i els fets quantitatius del proces.
-- El procediment esta pensat com a INSERT or UPDATE es a dir, si existeix el registre actualitza el camp de UPDATE mentre que si no existeix insereix la informacio i actualitza tant el camp de INSERT com el de UPDATE de la taula.
-- Quan estiguem en disposicio de poder actualitzar nomes els registres del periode carregat (malgrat inicialment es carrega tota la informacio des de origen per a cada dia) el procediment funcionara i millorara el seu rendiment de forma optima.

merge into
    db_uoc_prod.dd_od.fact_docencia
using
(select id_docencia,  
        id_semestre,  
        id_assignatura,  
        id_qualificacio,  
        id_qualificacio_continuada,  
        id_expedient,  
        id_matricula,  
        id_portafoli_pa,  
        id_persona_estudiant,  
        id_pais_nacionalitat,  
        id_pais_naixement,  
        id_pais_residencia,  
        id_acces,  
        id_persona_tutor,  
        nota_mitjana,  
        nota_mitjana_punts,  
        --any_acad_titol,  
        --any_academic,  
        --any_acad_valida,  
        --cod_assignatura,  
        assignatura_cursada,  
        num_credits,  
        num_credits_teorics,  
        num_credits_practics,  
        num_matriculas_assignatura,  
        semestre_relatiu_expedient,  
        semestre_relatiu_super_expedient,  
        semestre_relatiu_uoc,  
       --assigna_clase,  
       --cod_aula,  
       --cod_tfc,  
       --ind_sols_examen,  
        qualif_num_cont,  
        qualif_num_cont_final,  
        qualif_numerica,  
        qualif_numerica_pub,  
        qualif_num_practica,  
        qualif_num_pres,  
        qualif_num_prop,  
        qualif_num_teorica,  
      --qualif_practica,  
      --qualif_teorica,  
      --cod_qualif_conf,  
      --dim_qualificacio_continuada_key,  
      --cod_qualif_cont,  
      --dim_qualificacio_key,  
      --ind_supera,  
        supera_assignatura,  
        no_supera_assignatura,  
      --cod_qualificacio_pub,  
      --cod_qualif_pres,  
      --cod_qualif_prop,  
      --cod_examen,  
      --idp_corrector,  
        matricula_anulada,  
        assignatura_anulada,  
        assignatura_convalidada,  
        edat_relativa,  
        grup_edat,  
        grup_edat_2
from db_uoc_prod.dd_od.stage_docencia_post) as stage_docencia_post
on fact_docencia.id_docencia = stage_docencia_post.id_docencia
when matched then
    update
    set
        id_semestre = stage_docencia_post.id_semestre,  
        id_assignatura = stage_docencia_post.id_assignatura,  
        id_qualificacio = stage_docencia_post.id_qualificacio,  
        id_qualificacio_continuada = stage_docencia_post.id_qualificacio_continuada,  
        id_expedient = stage_docencia_post.id_expedient,  
        id_matricula = stage_docencia_post.id_matricula,  
        id_portafoli_pa = stage_docencia_post.id_portafoli_pa,  
        id_persona_estudiant = stage_docencia_post.id_persona_estudiant,  
        id_pais_nacionalitat = stage_docencia_post.id_pais_nacionalitat,  
        id_pais_naixement = stage_docencia_post.id_pais_naixement,  
        id_pais_residencia = stage_docencia_post.id_pais_residencia,  
        id_acces = stage_docencia_post.id_acces,  
        id_persona_tutor = stage_docencia_post.id_persona_tutor,  
        nota_mitjana = stage_docencia_post.nota_mitjana,  
        nota_mitjana_punts = stage_docencia_post.nota_mitjana_punts,  
        assignatura_cursada = stage_docencia_post.assignatura_cursada,  
        num_credits = stage_docencia_post.num_credits,  
        num_credits_teorics = stage_docencia_post.num_credits_teorics,  
        num_credits_practics = stage_docencia_post.num_credits_practics,  
        semestre_relatiu_expedient = stage_docencia_post.semestre_relatiu_expedient,  
        semestre_relatiu_super_expedient = stage_docencia_post.semestre_relatiu_super_expedient,  
        semestre_relatiu_uoc = stage_docencia_post.semestre_relatiu_uoc,  
        num_matriculas_assignatura = stage_docencia_post.num_matriculas_assignatura,  
        qualif_num_cont = stage_docencia_post.qualif_num_cont,  
        qualif_num_cont_final = stage_docencia_post.qualif_num_cont_final,  
        qualif_numerica = stage_docencia_post.qualif_numerica,  
        qualif_numerica_pub = stage_docencia_post.qualif_numerica_pub,  
        qualif_num_practica = stage_docencia_post.qualif_num_practica,  
        qualif_num_pres = stage_docencia_post.qualif_num_pres,  
        qualif_num_prop = stage_docencia_post.qualif_num_prop,  
        qualif_num_teorica = stage_docencia_post.qualif_num_teorica,  
        --dim_qualificacio_continuada_key = stage_docencia_post.dim_qualificacio_continuada_key,  
        --cod_qualif_cont = stage_docencia_post.cod_qualif_cont,  
        --dim_qualificacio_key = stage_docencia_post.dim_qualificacio_key,  
        supera_assignatura = stage_docencia_post.supera_assignatura,  
        no_supera_assignatura = stage_docencia_post.no_supera_assignatura,  
        matricula_anulada = stage_docencia_post.matricula_anulada,  
        assignatura_anulada = stage_docencia_post.assignatura_anulada,  
        assignatura_convalidada = stage_docencia_post.assignatura_convalidada,  
        edat_relativa = stage_docencia_post.edat_relativa,  
        grup_edat = stage_docencia_post.grup_edat,  
        grup_edat_2 = stage_docencia_post.grup_edat_2,  
        update_date = CONVERT_TIMEZONE(''America/Los_Angeles'', ''Europe/Madrid'', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ)  
    WHEN NOT MATCHED THEN
    INSERT
        (id_docencia,  
        id_semestre,  
        id_assignatura,  
        id_qualificacio,  
        id_qualificacio_continuada,  
        id_expedient,  
        id_matricula,  
        id_portafoli_pa,  
        id_persona_estudiant,  
        id_pais_nacionalitat,  
        id_pais_naixement,  
        id_pais_residencia,  
        id_acces,  
        id_persona_tutor,  
        nota_mitjana,  
        nota_mitjana_punts,  
        assignatura_cursada,  
        num_credits,  
        num_credits_teorics,  
        num_credits_practics,  
        semestre_relatiu_expedient,  
        semestre_relatiu_super_expedient,  
        semestre_relatiu_uoc,  
        num_matriculas_assignatura,  
        qualif_num_cont,  
        qualif_num_cont_final,  
        qualif_numerica,  
        qualif_numerica_pub,  
        qualif_num_practica,  
        qualif_num_pres,  
        qualif_num_prop,  
        qualif_num_teorica,  
        --dim_qualificacio_continuada_key,  
        --cod_qualif_cont,  
        --dim_qualificacio_key,  
        supera_assignatura,  
        no_supera_assignatura,  
        matricula_anulada,  
        assignatura_anulada,  
        assignatura_convalidada,  
        edat_relativa,  
        grup_edat,  
        grup_edat_2,  
        creation_date,  
        update_date  
        )
    values
        (stage_docencia_post.id_docencia,  
        stage_docencia_post.id_semestre,  
        stage_docencia_post.id_assignatura,  
        stage_docencia_post.id_qualificacio,  
        stage_docencia_post.id_qualificacio_continuada,  
        stage_docencia_post.id_expedient,  
        stage_docencia_post.id_matricula,  
        stage_docencia_post.id_portafoli_pa,  
        stage_docencia_post.id_persona_estudiant,  
        stage_docencia_post.id_pais_nacionalitat,  
        stage_docencia_post.id_pais_naixement,  
        stage_docencia_post.id_pais_residencia,  
        stage_docencia_post.id_acces,  
        stage_docencia_post.id_persona_tutor,  
        stage_docencia_post.nota_mitjana,  
        stage_docencia_post.nota_mitjana_punts,  
        stage_docencia_post.assignatura_cursada,  
        stage_docencia_post.num_credits,  
        stage_docencia_post.num_credits_teorics,  
        stage_docencia_post.num_credits_practics,  
        stage_docencia_post.semestre_relatiu_expedient,  
        stage_docencia_post.semestre_relatiu_super_expedient,  
        stage_docencia_post.semestre_relatiu_uoc,  
        stage_docencia_post.num_matriculas_assignatura,  
        stage_docencia_post.qualif_num_cont,  
        stage_docencia_post.qualif_num_cont_final,  
        stage_docencia_post.qualif_numerica,  
        stage_docencia_post.qualif_numerica_pub,  
        stage_docencia_post.qualif_num_practica,  
        stage_docencia_post.qualif_num_pres,  
        stage_docencia_post.qualif_num_prop,  
        stage_docencia_post.qualif_num_teorica,  
        --stage_docencia_post.dim_qualificacio_continuada_key,  
        --stage_docencia_post.cod_qualif_cont,  
        --stage_docencia_post.dim_qualificacio_key,  
        stage_docencia_post.supera_assignatura,  
        stage_docencia_post.no_supera_assignatura,  
        stage_docencia_post.matricula_anulada,  
        stage_docencia_post.assignatura_anulada,  
        stage_docencia_post.assignatura_convalidada,  
        stage_docencia_post.edat_relativa,  
        stage_docencia_post.grup_edat,  
        stage_docencia_post.grup_edat_2,  
        CONVERT_TIMEZONE(''America/Los_Angeles'',''Europe/Madrid'', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ), 
        CONVERT_TIMEZONE(''America/Los_Angeles'',''Europe/Madrid'', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ) 
        )
;

execution_time := datediff(millisecond, start_time, convert_timezone(''America/Los_Angeles'',''Europe/Madrid'', current_timestamp()::timestamp_ntz));

insert into db_uoc_prod.dd_od.procedures_log (id_log, procedure_name, executed_by, execution_date, execution_time, remarks)
    values (db_uoc_prod.dd_od.sequencia_id_log.nextval, ''full_docencia_data_load'', current_user(), :start_time, :execution_time, ''full_docencia_data_load Success'');
    
return ''Update completed successfully'';

end';